import = [
  "~/.config/alacritty/themes/themes/iterm.toml"
]

live_config_reload = true

[selection]
save_to_clipboard = true

[env]
TERM = "xterm-256color"

[font]
size = 16
normal      = { family = "UbuntuMono Nerd Font", style = "Regular" }
bold        = { family = "UbuntuMono Nerd Font", style = "Bold" }
italic      = { family = "UbuntuMono Nerd Font", style = "Italic" }
bold_italic = { family = "UbuntuMono Nerd Font", style = "Bold Italic" }

[window]
decorations = "buttonless"
startup_mode = "Maximized"
dynamic_padding = false
opacity = 0.95

[window.padding]
x = 7
y = 0

[keyboard]
bindings = [
	{ action = "ToggleFullscreen", key = "Return", mods = "Command" },
	{ action = "SpawnNewInstance", key = "N", mods = "Command" }
]
