# .zshrc is for interactive shells

# uncomment to start profiling 
# zmodload zsh/zprof

# see options for zsh on sharing history https://zsh.sourceforge.io/Doc/Release/Options.html#History
# SHELL_SESSIONS_DISABLE=1 should also be set in .zshenv on macOs
setopt SHARE_HISTORY

# alias tmux='tmux -f ~/.config/tmux/tmux.conf'

# add ~/.local/bin to $PATH if it exists
[[ -d ~/.local/bin ]] && path=(~/.local/bin $path)

# add brew to $PATH (prezto brew module needs it on the path)
#[[ -d /opt/homebrew ]] && eval "$(/opt/homebrew/bin/brew shellenv)"
#[[ -d ~/.linuxbrew ]] && eval "$(~/.linuxbrew/bin/brew shellenv)"

# zgenom - an optimized zsh package manager
export ZGEN_DIR=$XDG_DATA_HOME/zgenom
[[ ! -d $ZGEN_DIR ]] && git clone https://github.com/jandamm/zgenom.git "$ZGEN_DIR"
source "$ZGEN_DIR/zgenom.zsh"
zgenom autoupdate
if ! zgenom saved; then
  zgenom compdef

  # prezto
  zgenom prezto editor dot-expansion yes
  zgenom prezto prompt theme sorin

  zmodload zsh/terminfo

  # Load some oh-my-zsh plugins
  zgenom ohmyzsh plugins/ssh-agent
  zgenom ohmyzsh plugins/colored-man-pages
  zgenom ohmyzsh plugins/brew
  if [[ $(uname -a | grep -ci Darwin) = 1 ]]; then
    zgenom ohmyzsh plugins/macos
  fi

  # load after omz
  zgenom prezto

  # everything else
  zgenom load zsh-users/zsh-completions src
  zgenom load zsh-users/zsh-syntax-highlighting
  zgenom load zsh-users/zsh-history-substring-search
  zgenom load jonmosco/kube-ps1

  zgenom save
  zgenom compile $ZDOTDIR/.zshrc
  zgenom compile $ZDOTDIR
fi

# prompt config
RPROMPT='$(kube_ps1)'$RPROMPT

# ssh-agent config
zstyle :omz:plugins:ssh-agent agent-forwarding yes
zstyle :omz:plugins:ssh-agent helper ksshaskpass
zstyle :omz:plugins:ssh-agent lazy yes
zstyle :omz:plugins:ssh-agent ssh-add-args --apple-load-keychain

# go config
if command -v goenv > /dev/null; then
  eval "$(goenv init -)"
fi

# never generate .pyc files: it's slower, but maintains your sanity
if command -v python > /dev/null; then export PYTHONDONTWRITEBYTECODE=1; fi

# lazy load pyenv
export PYENV_ROOT=${PYENV_ROOT:-$XDG_DATA_HOME/pyenv}
[[ -a "$PYENV_ROOT/bin/pyenv" ]] && path=("$PYENV_ROOT/bin" $path)
if type pyenv &> /dev/null || [[ -a $PYENV_ROOT/bin/pyenv ]]; then
  function pyenv() {
    unset pyenv
    path=("$PYENV_ROOT/shims" $path)
    eval "$(command pyenv init -)"
    if command -v pyenv-virtualenv-init > /dev/null; then
      eval "$(pyenv virtualenv-init -)"
      export PYENV_VIRTUALENV_DISABLE_PROMPT=1
    fi
    pyenv "$@"
  }
fi

# lazy load rbenv
export RBENV_ROOT=${RBENV_ROOT:-$XDG_DATA_HOME/rbenv}
[[ -a $RBENV_ROOT/bin/rbenv ]] && path=("$RBENV_ROOT/bin" $path)
if type rbenv &> /dev/null || [[ -a $RBENV_ROOT/bin/rbenv ]]; then
  function rbenv() {
    unset rbenv
    path=("$RBENV_ROOT/shims" $path)
    eval "$(command rbenv init -)"
  }
fi

# zsh keybinds
bindkey '^[[H' beginning-of-line # Home
bindkey '^[[F' end-of-line       # End
# mac-style text navigation for minimal terminal emulators
bindkey "\e[1;3D" backward-word # ⌥←
bindkey "\e[1;3C" forward-word  # ⌥→
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
#bindkey '^[[A' history-substring-search-up
#bindkey '^[[B' history-substring-search-down

if [[ ! -z "$ZSH_VERSION" ]]; then
  # all of our zsh files
  typeset -U config_files
  config_files=($DOTFILES/**/*.zsh)

  # load the path files
  for file in ${(M)config_files:#*/path.zsh}
  do
    source $file
  done

  # load everything but the path and completion files
  for file in ${${config_files:#*/path.zsh}:#*/completion.zsh}
  do
    source $file
  done

  # initialize autocomplete here, otherwise functions won't be loaded
  autoload -U compinit
  compinit

  # load every completion after autocomplete loads
  for file in ${(M)config_files:#*/completion.zsh}
  do
    source $file
  done

  unset config_files
fi

# Stash your environment variables in ~/.localrc. This means they'll stay out
# of your main dotfiles repository (which may be public, like this one), but
# you'll have access to them in your scripts.
if [[ -a ~/.localrc ]]; then
  source ~/.localrc
fi

# 1password plugins
if [[ -f ~/.config/op/plugins.sh ]]; then
  source ~/.config/op/plugins.sh
fi

# uncomment to complete profiling
# zprof

