cask "1password"
cask "1password-cli"
cask "obsidian"
cask "spotify"
cask "vlc"

if OS.mac?
  cask "amethyst"
  cask "sanesidebuttons"

  brew "mas"
  # https://github.com/mas-cli/mas?tab=readme-ov-file#-using-tmux
  brew "reattach-to-user-namespace"

  if system 'defaults read MobileMeAccounts Accounts | grep AccountID', :out => File::NULL, :err => File::NULL
    mas "1Password for Safari", id: 1569813296
    mas "AdBlock", id: 1402042596
    mas "DuckDuckGo Privacy for Safari", id: 1482920575
    mas "TripMode", id: 1513400665
    mas "‎WhatsApp", id: 310633997
  else
    STDERR.puts "\e[31mNo Apple ID configured - cannot install Apple Store Apps using brew/mas\e[0m"
  end
end
