#!/bin/bash
#
# bootstrap installs things.

set -e

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

source bin/link-file
source bin/pretty-log

echo ''

setup_gitconfig () {
  if ! [ -f git/gitconfig.local.symlink ]
  then
    info 'setup gitconfig'

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi

    user ' - What is your github author name?'
    read -e git_authorname
    user ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink

    success 'gitconfig'
  fi
}

symlink_dotfiles () {
  info 'installing dotfiles'

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

install_zsh_configs () {
  info 'installing zsh configs'

  source ~/.zshenv

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "zsh/configs" -maxdepth 1)
  do
    dst="$ZDOTDIR/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

setup_gitconfig
symlink_dotfiles
install_zsh_configs

# If we're on a Mac, let's install and setup homebrew.
if [ "$(uname -s)" == "Darwin" ]
then
  info "installing dependencies"
  if source bin/dot | while read -r data; do info "$data"; done
  then
    success "dependencies installed"
  else
    fail "error installing dependencies"
  fi
fi

echo ''
echo '  All installed!'
