#!/bin/sh
#
# bootstrap installs things.

set -e

cd "$(dirname "$0")/.."
DOTFILES=$(pwd -P)

source bin/link-file
source bin/pretty-log

setup_gitconfig () {
  if ! [ -f git/gitconfig.local.symlink ]
  then
    info 'setup gitconfig'

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi

    user ' - What is your github author name?'
    read -e git_authorname
    user ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink

    success 'completed gitconfig setup'
  fi
}

symlink_dotfiles () {
  info 'installing dotfiles'

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

install_zsh_configs () {
  info 'installing zsh configs'

  if [[ ! -z "$ZDOTDIR" ]]; then
    fail '$ZDOTDIR is already set in environment - this will conflict with .zshenv!' 
  fi

  source ~/.zshenv

  if [[ -z "$ZDOTDIR" ]]; then
    fail '$ZDOTDIR is not set in .zshenv!'
  fi

  mkdir -p "$ZDOTDIR"

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES/zsh/configs" -mindepth 1)
  do
    dst="$ZDOTDIR/.$(basename "$src")"
    link_file "$src" "$dst"
  done
}

run_setup () {
  info "installing dependencies"
  if source bin/dot | while read -r data; do info "$data"; done
  then
    success "dependencies installed"
  else
    fail "error installing dependencies"
  fi
}

echo ''
setup_gitconfig
echo ''
symlink_dotfiles
echo ''
install_zsh_configs
echo ''
run_setup
echo ''
success 'All installed!'
